### ISSUE TITLE
Update Magic Link to work on the latest version of Statamic

### ISSUE THREAD

**Issue by Qeria** [codedge/statamic-magiclink#255]
Hello, 
I'm facing this issue when trying to install. I do have the latest 4.23.2 version, and I'm looking for your help.

![Screen Shot 2023-09-22 at 8 02 48 PM](https://github.com/codedge/statamic-magiclink/assets/648164/86766b3c-2531-4d3a-ae81-4bbe96a61829)

**Comment by codedge** [comment]
Fixed
