### ISSUE TITLE
Whitelisting email domain

### ISSUE THREAD

**Issue by ghost** [codedge/statamic-magiclink#78]
Hallo,

We are very interested by your MagicLink addon. Do you think if it's possible to use an email domain instead of declaring all the accounts that should have access to the Statamic website?

Maybe it's technicaly not possible?

Thanks

**Comment by codedge** [comment]
Hey @Pascal997 

I think that is definitely possible. I'll have a look over the weekend!

**Comment by Pascal997** [comment]
Excellent @codeedge, thanks!

**Comment by codedge** [comment]
@Pascal997 Just to get this right:

You like to specify a global domain for which your _already registered_ Control Panel user can get a magic link to login, right?

Example:

Registered users are:

- tom@domain1.com
- paul@domain1.com
- tina@domain2.com

By specifying _domain2.com_ only Tina would be able to receive a magic link to login. Tom and Paul can only login via username+password.

**Comment by Pascal997** [comment]
The thing is, we do not want to create our 1800 employee accounts in the CMS. It's why the authorization by domain only could be a better solution for us. We have something like 5 or 6 domains at all.

**Comment by codedge** [comment]
Understood. Then the I PR I created is sth. for you 😉 
I'll wrap it up and merge it. And then you're good to go.

**Comment by codedge** [comment]
Please check it out. You can now configure domains in the backend. As there is no validation, entered domains should be in format `example.com` - nothing else. Just to mention this. 😄

**Comment by Pascal997** [comment]
Ok thanks, I'll test it
